iterations from 1 to 3 changes
ddyachkov/url-shortener pull request #1
Opened 2023-01-31 20:30 UTC by ddyachkov

2023-02-01 19:55 UTC, molchalin requested changes

2023-02-01 19:55 UTC, molchalin commented on cmd/shortener/main.go
> +	router.Method("POST", "/", handler)
```suggestion
	router.Method(http.MethodPost, "/", handler)
```

2023-02-01 19:55 UTC, molchalin commented on cmd/shortener/main.go
> +	router.Method("GET", "/{URI}", handler)
А в чем смысл роутинга, если это все равно приходит в один и тот же хендлер?

2023-02-01 19:55 UTC, molchalin commented on internal/handlers/handlers.go
> +	switch r.Method {
Давай разнесём это по отдельным хендлерам

2023-02-01 19:55 UTC, molchalin commented on internal/handlers/handlers.go
> +			writeResponce(w, http.StatusBadRequest, err.Error())
```suggestion
			http.Error(w, http.StatusBadRequest, err.Error())
```

2023-02-01 19:55 UTC, molchalin commented on internal/handlers/handlers.go
> +			writeResponce(w, http.StatusBadRequest, err.Error())
А если такого урла не было?

2023-02-01 19:55 UTC, molchalin commented on internal/app/urlshortener.go
> +	WriteData(string) int
Представь, что завтра придёт задание сделать реализацию для этого  интерфейса для БД, а БД может вернуть ошибку

2023-02-01 19:55 UTC, molchalin commented on internal/app/urlshortener.go
> +func validLink(link string) bool {
Для этого есть `net/url`

2023-02-02 04:00 UTC, ddyachkov commented on cmd/shortener/main.go
> +	router.Method("GET", "/{URI}", handler)
В первом инкременте был роутинг на один хэндлер и внутри проверялся URL на наличие URI, в зависимости от проверки возвращалась ошибка о неправильном HTTP методе. В третьем инкременте сделал так потому что модуль chi при таком использовании берет обработку неправильного метода на себя.

2023-02-02 05:08 UTC, ddyachkov commented on internal/handlers/handlers.go
> +			writeResponce(w, http.StatusBadRequest, err.Error())
Не очень понял вопроса. Если по URI через GetFullURL не найдется URL, то ведь ошибка вернется.

2023-02-02 10:02 UTC, ddyachkov commented on internal/handlers/handlers.go
> +	switch r.Method {
Разделил на два хэндлера

2023-02-02 10:03 UTC, ddyachkov commented on internal/app/urlshortener.go
> +	WriteData(string) int
Добавил в возвращаемые параметры метода error

2023-02-02 10:06 UTC, ddyachkov commented on internal/app/urlshortener.go
> +func validLink(link string) bool {
Переделал на использование функции `ParseRequestURI `пакета `net/url`. Если честно не очень понравилась как работает, URL вида "https:www.google.ru" вполне пропускает.

2023-02-02 10:07 UTC, ddyachkov commented on cmd/shortener/main.go
> +	router.Method("GET", "/{URI}", handler)
С разделением на два хэндлера вопрос можно закрывать?

2023-02-03 06:00 UTC, molchalin commented on internal/handlers/handlers.go
> +			writeResponce(w, http.StatusBadRequest, err.Error())
Да, но это не 400(Bad request) должно быть, а 404(Not found)

2023-02-03 06:03 UTC, molchalin commented on internal/app/urlshortener.go
> +func validLink(link string) bool {
браузер тоже такой url обрабатывает. При желании можно поизучать RFC и понять, какое поведение тут правильное)

2023-02-03 16:58 UTC, ddyachkov commented on internal/handlers/handlers.go
> +			writeResponce(w, http.StatusBadRequest, err.Error())
Изменил код 400 на 404

2023-02-03 16:59 UTC, merged